image: debian/testing
packages:
  - emacs
  - rsync
  - texinfo
  - texlive
sources:
  - https://git.sr.ht/~codegouvfr/superset-docs
secrets:
  - bdd50953-add5-4ddb-9f34-9f0781900b7e
tasks:
  - install: |
      cd superset-docs/
      emacs --script scripts/publish.el
      texi2pdf index.texi
      mv index.pdf superset-docs.pdf
  - upload: |
      rsync -e "ssh -o StrictHostKeyChecking=no" -av superset-docs/* web@code.gouv.fr:/home/web/websites/superset-docs/
triggers:
  - action: email
    condition: failure
    to: bastien.guerry@code.gouv.fr
